type TeslaModelX {
  Typ: String
  Art: String
  Tarif: String
  Beschreibung: String
  Inklusivkilometer: String
  Preis: String
  PreisproTag: String
}

type TeslaModel3Performance {
  Typ: String
  Art: String
  Tarif: String
  Beschreibung: String
  Inklusivkilometer: String
  Preis: String
  PreisproTag: String
}

type TeslaModel3SRPlus {
  Typ: String
  Art: String
  Tarif: String
  Beschreibung: String
  Inklusivkilometer: String
  Preis: String
  PreisproTag: String
}

type TeslaModel3LongRange {
  Typ: String
  Art: String
  Tarif: String
  Beschreibung: String
  Inklusivkilometer: String
  Preis: String
  PreisproTag: String
}

type Query {
  TeslaModelX: [TeslaModelX]
  TeslaModel3Performance: [TeslaModel3Performance]
  TeslaModel3SRPlus: [TeslaModel3SRPlus]
  TeslaModel3LongRange: [TeslaModel3LongRange]
  TeslaModelXbyArt(Art: String): [TeslaModelX]
  TeslaModel3PerformancebyArt(Art: String): [TeslaModel3Performance]
  TeslaModel3SRPlusbyArt(Art: String): [TeslaModel3SRPlus]
  TeslaModel3LongRangebyArt(Art: String): [TeslaModel3LongRange]
  TeslaModelXbyLowestPrice(Art: String, Beschreibung: String): [TeslaModelX]
  TeslaModel3PerformancebyLowestPrice(
    Art: String
    Beschreibung: String
  ): [TeslaModel3Performance]
  TeslaModel3SRPlusbyLowestPrice(
    Art: String
    Beschreibung: String
  ): [TeslaModel3SRPlus]
  TeslaModel3LongRangebyLowestPrice(
    Art: String
    Beschreibung: String
  ): [TeslaModel3LongRange]
}
