name: upload2HosterOld

on:
  push:
    branches: [master]

jobs:
  Cypress-Build-Test:
    name: Cypress Build and Test
    runs-on: ubuntu-latest
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run 3 copies of the current job in parallel
        containers: [1, 2, 3]
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 1

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Build Project
        env:
          RELATIVE_CI_KEY: ${{ secrets.RELATIVE_CI_KEY }}
        run: |
          npm install
          npm run build --if-present

      - name: List output files
        run: ls -lS
      - name: Cypress Run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          record: true
          parallel: true
          group: 'mobility all tests'
          start: 'npm run start' # start server before running tests
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: List output files
        run: ls -lS

  DeployFTP:
    name: Deploy via FTP
    runs-on: ubuntu-latest
    needs: [Cypress-Build-Test]
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 1

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Build Project
        env:
          RELATIVE_CI_KEY: ${{ secrets.RELATIVE_CI_KEY }}
        run: |
          npm install
          npm run build --if-present
          npx relative-ci-agent

      - name: list files
        run: ls -lS
      - name: Upload FTP
        uses: kevinpainchaud/simple-ftp-deploy-action@v1.1.0
        with:
          ftp_host: ${{ secrets.HOST }}
          ftp_username: ${{ secrets.USERNAME }}
          ftp_password: ${{ secrets.PASSWORD }}
          local_source_dir: 'out'
          dist_target_dir: '/'
          delete: 'true'
          exclude: "'^logs/' '^README.md' 'stats.json' 'webpack.stats.json'"
